/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: ict@salvemundi.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs";

import { map } from "rxjs/operators";
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { PageView } from "../model/pageView";

import { COLLECTION_FORMATS }  from "../variables";



@injectable()
export class StatisticService {
    private basePath: string = 'http://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }

    /**
     * GetAll
     * This call can be used to get all the pageview statistics
     
     */
    public pageViewGetAll(observe?: 'body', headers?: Headers): Observable<Array<PageView>>;
    public pageViewGetAll(observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<PageView>>>;
    public pageViewGetAll(observe: any = 'body', headers: Headers = {}): Observable<any> {
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<PageView>>> = this.httpClient.get(`${this.basePath}/statistic/pageview`, headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <Array<PageView>>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * create
     * This call can be used to add the pageview
     
     */
    public pageViewNew(observe?: 'body', headers?: Headers): Observable<any>;
    public pageViewNew(observe?: 'response', headers?: Headers): Observable<HttpResponse<any>>;
    public pageViewNew(observe: any = 'body', headers: Headers = {}): Observable<any> {
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<any>> = this.httpClient.post(`${this.basePath}/statistic/pageview`, headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <any>(httpResponse.response))
               );
        }
        return response;
    }

}
