/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ict@salvemundi.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";

import { map } from "rxjs/operators";
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { ShortedUserDto } from "../model/shortedUserDto";
import { UpdateUserDto } from "../model/updateUserDto";
import { User } from "../model/user";

import { COLLECTION_FORMATS }  from "../variables";



@injectable()
export class UserService {
    private basePath: string = 'http://localhost';

    constructor(@inject("IApiHttpClient") private httpClient: IHttpClient,
        @inject("IAPIConfiguration") private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }

    /**
     * getAll
     * This call is used to get a summary of all the users
     * @param take 
     * @param skip 
     
     */
    public userGet(take: number, skip: number, observe?: 'body', headers?: Headers): Observable<Array<ShortedUserDto>>;
    public userGet(take: number, skip: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<ShortedUserDto>>>;
    public userGet(take: number, skip: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (take === null || take === undefined){
            throw new Error('Required parameter take was null or undefined when calling userGet.');
        }

        if (skip === null || skip === undefined){
            throw new Error('Required parameter skip was null or undefined when calling userGet.');
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<ShortedUserDto>>> = this.httpClient.get(`${this.basePath}/user`, headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <Array<ShortedUserDto>>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * delete
     * This call is used to delete a user
     * @param id 
     
     */
    public userIdDelete(id: number, observe?: 'body', headers?: Headers): Observable<any>;
    public userIdDelete(id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<any>>;
    public userIdDelete(id: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (id === null || id === undefined){
            throw new Error('Required parameter id was null or undefined when calling userIdDelete.');
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<any>> = this.httpClient.delete(`${this.basePath}/user/${encodeURIComponent(String(id))}`, headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <any>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * getOne
     * This call is used to get a specific user
     * @param id 
     
     */
    public userIdGet(id: number, observe?: 'body', headers?: Headers): Observable<User>;
    public userIdGet(id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<User>>;
    public userIdGet(id: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (id === null || id === undefined){
            throw new Error('Required parameter id was null or undefined when calling userIdGet.');
        }

        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<User>> = this.httpClient.get(`${this.basePath}/user/${encodeURIComponent(String(id))}`, headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <User>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * me
     * This call is used to get the current user
     
     */
    public userMeGet(observe?: 'body', headers?: Headers): Observable<User>;
    public userMeGet(observe?: 'response', headers?: Headers): Observable<HttpResponse<User>>;
    public userMeGet(observe: any = 'body', headers: Headers = {}): Observable<any> {
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<User>> = this.httpClient.get(`${this.basePath}/user/me`, headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <User>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * update
     * This call is used to update a user
     * @param updateUserDto 
     
     */
    public userPut(updateUserDto: UpdateUserDto, observe?: 'body', headers?: Headers): Observable<User>;
    public userPut(updateUserDto: UpdateUserDto, observe?: 'response', headers?: Headers): Observable<HttpResponse<User>>;
    public userPut(updateUserDto: UpdateUserDto, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (updateUserDto === null || updateUserDto === undefined){
            throw new Error('Required parameter updateUserDto was null or undefined when calling userPut.');
        }

        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<User>> = this.httpClient.put(`${this.basePath}/user`, updateUserDto , headers);
        if (observe == 'body') {
               return response.pipe(
                   map(httpResponse => <User>(httpResponse.response))
               );
        }
        return response;
    }

}
