// tslint:disable
/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Committee
 */
export interface Committee {
    /**
     * @type {number}
     * @memberof Committee
     */
    id: number;
    /**
     * @type {string}
     * @memberof Committee
     */
    name: string;
    /**
     * @type {string}
     * @memberof Committee
     */
    description: string;
    /**
     * @type {Date}
     * @memberof Committee
     */
    created: Date;
}
