// tslint:disable
/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CreateCommissionDto
 */
export interface CreateCommissionDto {
    /**
     * @type {string}
     * @memberof CreateCommissionDto
     */
    name: string;
    /**
     * @type {string}
     * @memberof CreateCommissionDto
     */
    description: string;
}
