// tslint:disable
/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LoginDTO
 */
export interface LoginDTO {
    /**
     * @type {string}
     * @memberof LoginDTO
     */
    email: string;
    /**
     * @type {string}
     * @memberof LoginDTO
     */
    password: string;
}
