// tslint:disable
/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Scope
 */
export interface Scope {
    /**
     * @type {number}
     * @memberof Scope
     */
    id: number;
    /**
     * @type {string}
     * @memberof Scope
     */
    name: string;
}
