// tslint:disable
/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ShortedUserDto
 */
export interface ShortedUserDto {
    /**
     * @type {number}
     * @memberof ShortedUserDto
     */
    id: number;
    /**
     * @type {string}
     * @memberof ShortedUserDto
     */
    pcn: string;
    /**
     * @type {string}
     * @memberof ShortedUserDto
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof ShortedUserDto
     */
    lastName: string;
    /**
     * @type {Date}
     * @memberof ShortedUserDto
     */
    registeredSince: Date;
}
