// tslint:disable
/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Scope,
} from './';

/**
 * @export
 * @interface User
 */
export interface User {
    /**
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * @type {string}
     * @memberof User
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof User
     */
    lastName: string;
    /**
     * @type {Date}
     * @memberof User
     */
    birthday: Date;
    /**
     * @type {string}
     * @memberof User
     */
    address: string;
    /**
     * @type {string}
     * @memberof User
     */
    postalcode: string;
    /**
     * @type {string}
     * @memberof User
     */
    city: string;
    /**
     * @type {string}
     * @memberof User
     */
    country: string;
    /**
     * @type {string}
     * @memberof User
     */
    phoneNumber: string;
    /**
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * @type {Date}
     * @memberof User
     */
    registeredSince: Date;
    /**
     * @type {string}
     * @memberof User
     */
    pcn: string;
    /**
     * @type {Array<Scope>}
     * @memberof User
     */
    scopes: Array<Scope>;
}
