/**
 * Salve mundi API
 * Salve mundi API documentation
 *
<<<<<<< HEAD
 * The version of the OpenAPI document: 1.0.0
=======
 * The version of the OpenAPI document: 1.1.1-beta1
>>>>>>> master
 * Contact: ict@salvemundi.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddMutationDTO { 
    description: string;
    entryReference?: number;
    date: string;
    amount: number;
    debtorIban: string;
    paymentMethodId: number;
    incomeStatementId: number;
}
