/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 2.4.1-beta11
 * Contact: ict@salvemundi.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDTO { 
    firstName: string;
    lastName: string;
    birthday: string;
    address: string;
    city: string;
    postalcode: string;
    country: string;
    email: string;
    phoneNumber: string;
    pcn: string;
    profilePicture: Blob;
}
