/**
 * Salve mundi API
 * Salve mundi API documentation
 *
 * The version of the OpenAPI document: 2.4.1-beta11
 * Contact: ict@salvemundi.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Membership } from './membership';


export interface User { 
    id: number;
    firstName: string;
    lastName: string;
    birthday: string;
    address: string;
    postalcode: string;
    city: string;
    country: string;
    phoneNumber: string;
    email: string;
    registeredSince: string;
    pcn: string;
    profilePicture: string;
    activated: boolean;
    memberships: Array<Membership>;
    transactions: Array<object>;
}
